#!/bin/bash
#PBS -lwalltime=48:00:00
#PBS -lselect=1:ncpus=10:mem=120gb
echo "Current date: $now"
echo "Loading Modules"

# source python virtual environment
source $WORK/test-env/bin/activate


cp $WORK/DiffusionProject/Evaluation/evaluate_variance_3D.py .

echo "exporting to PATH"
export PYTHONPATH="${PYTHONPATH}:/rds/general/user/db3115/home/"

echo "Running python"
python3 evaluate_variance_3D.py


echo "Copying files"
mkdir $WORK/$PBS_JOBID
cp -r * $WORK/$PBS_JOBID
echo "Done"