#!/bin/bash
#PBS -lselect=1:ncpus=16:mem=16gb
#PBS -lwalltime=24:00:00

echo "Loading Modules"

# source python virtual environment
source $WORK/test-env/bin/activate


cp $WORK/DiffusionProject/Evaluation/debugCPU.py .

echo "exporting to PATH"
export PYTHONPATH="${PYTHONPATH}:/rds/general/user/db3115/home/"

echo "Running python"
python3 debugCPU.py


echo "Copying files"
mkdir $WORK/Results/$PBS_JOBID
cp -r * $WORK/Results/$PBS_JOBID
echo "Done"