Name: "6qubits3D"
ExperimentParams:
  Type: Batch
  BatchParams:
    StepSize: 10
    StartIterations: 0
    MaxIterations: 200
  NDims: 3
  NQubits: 6
  Coin: "Hadamard"
  InitialStates: "auto"
  Boundaries:
    - Type: "Hard"
      Bitstring: "000000"
      Dim: 0
    - Type: "Hard"
      Bitstring: "111111"
      Dim: 0
    - Type: "Hard"
      Bitstring: "000000"
      Dim: 1
    - Type: "Hard"
      Bitstring: "111111"
      Dim: 1
    - Type: "Hard"
      Bitstring: "000000"
      Dim: 2
    - Type: "Hard"
      Bitstring: "111111"
      Dim: 2
  InitialState: "auto"
  Shots: 2048

JobParams:
  NCPUs: 32
  Memory: 32
  Walltime: 24
  BatchSize: 1
