Name: "9qubits2D_Grover"
ExperimentParams:
  Type: Batch
  BatchParams:
    StepSize: 10
    StartIterations: 0
    MaxIterations: 200
  NDims: 2
  NQubits: 9
  Coin: "Grover"
  InitialStates: "auto"
  Boundaries:
    - Type: "Hard"
      Bitstring: "000000000"
      Dim: 0
    - Type: "Hard"
      Bitstring: "111111111"
      Dim: 0
    - Type: "Hard"
      Bitstring: "000000000"
      Dim: 1
    - Type: "Hard"
      Bitstring: "111111111"
      Dim: 1

  InitialState: "auto"
  Shots: 2048

JobParams:
  NCPUs: 32
  Memory: 32
  Walltime: 36
  BatchSize: 1

KeepJobFiles: false