
ExperimentParams:
  Type: Batch
  BatchParams:
    StepSize: 10
    StartIterations: 0
    MaxIterations: 100
  NSteps: 10
  NDims: 2
  NQubits: 3
  Coin: "Hadamard"
  InitialStates: "auto"
  Boundaries:
    - Type: "Hard"
      Bitstring: "000"
      Dim: 0
    - Type: "Hard"
      Bitstring: "111"
      Dim: 0
    - Type: "Hard"
      Bitstring: "000"
      Dim: 1
    - Type: "Hard"
      Bitstring: "111"
      Dim: 1
  InitialState: "auto"
  Shots: 2048

JobParams:
  UseGPU: false
  GPUType: "K80"
  NGPUs: 1
  NCPUs: 8
  Memory: 16
  Walltime: 24
  NCores: 
  BatchSize: 5

