Name: "Soft_boundary_debug"
ExperimentParams:
  Type: Single
  NSteps: 20
  NDims: 1
  NQubits: 5
  Coin: "Hadamard"
  InitialStates: "auto"
  Boundaries:


    - Type: "Hard"
      Geometry: "Edges"
  

  InitialState: "auto"
  Shots: 2048
  DecoherenceIntervals: 6


JobParams:
  NCPUs: 32
  Memory: 16
  Walltime: 24
  BatchSize: 1

KeepJobFiles: true
OutputPath: "/Users/Ali/Downloads"